import React from 'react';
import { ArrowLeft, ShieldCheck, FileText, Scale, Info } from 'lucide-react';

interface TermsPageProps {
    onBack: () => void;
}

export const TermsPage: React.FC<TermsPageProps> = ({ onBack }) => {
    return (
        <div className="min-h-screen bg-[#ffffff] dark:bg-gray-950 text-gray-900 dark:text-gray-100 font-sans p-6 sm:p-12 animate-in fade-in duration-700">
            <div className="max-w-3xl mx-auto space-y-12">
                {/* Header */}
                <div className="flex items-center justify-between">
                    <button
                        onClick={onBack}
                        className="p-3 bg-gray-100 dark:bg-gray-900 rounded-2xl hover:scale-110 active:scale-95 transition-all text-gray-600 dark:text-gray-400"
                    >
                        <ArrowLeft size={20} />
                    </button>
                    <div className="flex items-center space-x-2 text-blue-600 font-black uppercase tracking-[0.3em] text-[10px]">
                        <ShieldCheck size={16} />
                        <span>Legal Center</span>
                    </div>
                </div>

                <div className="space-y-4">
                    <h1 className="text-4xl sm:text-5xl font-black uppercase tracking-tighter leading-none italic bg-gradient-to-r from-gray-900 to-gray-600 dark:from-white dark:to-gray-400 bg-clip-text text-transparent">
                        Terms & <br />Conditions
                    </h1>
                    <p className="text-[10px] font-bold text-gray-500 uppercase tracking-widest">Last Updated: February 19, 2026</p>
                </div>

                {/* Content Sections */}
                <div className="space-y-10">
                    <section className="space-y-4">
                        <div className="flex items-center space-x-3 text-blue-600">
                            <FileText size={18} />
                            <h2 className="text-sm font-black uppercase tracking-widest">1. Usage Rules</h2>
                        </div>
                        <p className="text-xs text-gray-600 dark:text-gray-400 leading-relaxed font-medium">
                            Photo to Emoji Studio is a creative tool designed to transform user-uploaded digital images into ASCII, Emoji, or Dot-based mosaics. By using this application, you agree to use it only for lawful purposes. You are prohibited from processing any material that violates intellectual property rights or contains harmful content.
                        </p>
                    </section>

                    <section className="space-y-4">
                        <div className="flex items-center space-x-3 text-purple-600">
                            <Scale size={18} />
                            <h2 className="text-sm font-black uppercase tracking-widest">2. User Responsibility</h2>
                        </div>
                        <p className="text-xs text-gray-600 dark:text-gray-400 leading-relaxed font-medium">
                            You are solely responsible for the content you upload and process. We do not preview, monitor, or moderate the images you choose to transform. You must ensure you have the necessary permissions for any images used within the studio.
                        </p>
                    </section>

                    <section className="space-y-4">
                        <div className="flex items-center space-x-3 text-green-600">
                            <ShieldCheck size={18} />
                            <h2 className="text-sm font-black uppercase tracking-widest">3. No Data Storage</h2>
                        </div>
                        <div className="p-4 bg-green-500/5 border border-green-500/20 rounded-2xl">
                            <p className="text-xs text-green-800 dark:text-green-400 leading-relaxed font-bold">
                                🔒 Privacy Guarantee: All image processing happens locally within your browser's Web Worker. We do not transmit, store, or sell your original or generated images to external servers. Your creativity remains your own.
                            </p>
                        </div>
                    </section>

                    <section className="space-y-4">
                        <div className="flex items-center space-x-3 text-orange-600">
                            <Info size={18} />
                            <h2 className="text-sm font-black uppercase tracking-widest">4. Intellectual Property</h2>
                        </div>
                        <p className="text-xs text-gray-600 dark:text-gray-400 leading-relaxed font-medium">
                            The "Photo to Emoji Studio" name, branding, logo, and source code are the intellectual property of our studio. Mosaics generated by the tool may be used for personal or commercial purposes, provided you own the rights to the original source image.
                        </p>
                    </section>

                    <section className="space-y-4">
                        <div className="flex items-center space-x-3 text-red-600">
                            <Scale size={18} />
                            <h2 className="text-sm font-black uppercase tracking-widest">5. Limitation of Liability</h2>
                        </div>
                        <p className="text-xs text-gray-600 dark:text-gray-400 leading-relaxed font-medium italic">
                            The application is provided "as is" without warranties of any kind. Under no circumstances shall Photo to Emoji Studio be liable for any damages resulting from the use or inability to use the service, including data loss or device performance issues during rendering.
                        </p>
                    </section>
                </div>

                {/* Footer */}
                <div className="pt-12 border-t border-gray-100 dark:border-gray-800 text-center">
                    <button
                        onClick={onBack}
                        className="px-8 py-4 bg-[#1a1a1a] dark:bg-white text-white dark:text-[#1a1a1a] rounded-2xl shadow-xl font-black uppercase tracking-widest text-[11px] hover:scale-105 active:scale-95 transition-all"
                    >
                        Accept & Return to Studio
                    </button>
                    <p className="mt-8 text-[9px] text-gray-400 font-bold uppercase tracking-[0.3em]">
                        © 2026 Photo to Emoji Studio • All Rights Reserved
                    </p>
                </div>
            </div>
        </div>
    );
};

export default TermsPage;
